### PR TITLE
Sourcing software developers.md

### PR DESCRIPTION
**Pull request by aruparell17**
Hey team - please provide me with comments on my contribution.

@noahlevy @claytonsachs @ljaronnecbs @gouthamvaleti

### CODE REVIEW

**Comment by claytonsachs** [comment]
I think this approach looks great @aruparell17

**Comment by gouthamvaleti** [comment]
@aruparell17 - Entering Hackathons with a business idea might be another alternative.

**Comment by noahlevy** [comment]
:+1:

**Comment by aruparell17** [comment]
@gouthamvaleti great suggestion

**Comment by aruparell17** [comment]
@gouthamvaleti @noahlevy @claytonsachs @ljaronnecbs  Gents - I've incorporated all feedback. Please give me a :+1: if this is good to ship!

**Comment by claytonsachs** [comment]
:+1:

**Pull request merged**
