### PR TITLE
Create Mobile apps Hybrid vs Native.md

### PR DESCRIPTION
**Pull request by noahlevy**
Throw your boy some comments...

@gouthamvaleti @claytonsachs @aruparell17 @ljaronnecbs

### CODE REVIEW

**Comment by noahlevy** [comment]
@aruparell17 - updated 1 and 2, let me know if i added the link and picture correctly.. I addressed your 3rd comment on line 35 - you wouldn't need separate dev teams necessarily. You could have an engineer who can code in objective-c and java..

**Comment by claytonsachs** [comment]
Yea great points from @noahlevy I added a picture and link in mine as well. I feel like @markzuckerberg

**Comment by noahlevy** [comment]
:+1:

**Comment by gouthamvaleti** [comment]
:+1: We're good to merge

**Pull request merged**
