### PR TITLE
Bootstrapping and mvps.md

### PR DESCRIPTION
**Pull request by claytonsachs**
Hey @gouthamvaleti @ljaronnecbs @noahlevy @aruparell17 can you guys provide feedback? Thanks!

### CODE REVIEW

**Comment by noahlevy** [comment]
Looks awesome - you might want to add other e-commerce solutions like Squarespace or Magento.

**Comment by gouthamvaleti** [comment]
@claytonsachs great explanation of why an MVP is useful and the risks we could face if the service scales up very quickly.

**Comment by noahlevy** [comment]
:+1:

**Comment by claytonsachs** [comment]
Can i get a thumbs up :+1: @gouthamvaleti ?

**Pull request merged**
